image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-backend:
  stage: build
  script:
    - docker build --pull -f _deployment/Dockerfile.node -t "$CI_REGISTRY_IMAGE/backend" .
    - docker push "$CI_REGISTRY_IMAGE/backend"
  only:
    - main

build-nginx:
  stage: build
  script:
    - docker build --pull -f _deployment/Dockerfile.nginx -t "$CI_REGISTRY_IMAGE/nginx" .
    - docker push "$CI_REGISTRY_IMAGE/nginx"
  only:
    - main
