name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          file: _deployment/Dockerfile.node
          tags: |
            ghcr.io/${{ github.repository }}/backend:latest
  nginx:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          file: _deployment/Dockerfile.nginx
          tags: |
            ghcr.io/${{ github.repository }}/nginx:latest
